### ISSUE TITLE
update werkzeug dependency

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#225]
## Description
Werkzeug 2.0.3 has a potential security vulnerability, we need to update to 2.1.1 and fix the test cases for that.

**Comment by LaurentMontBlanc** [comment]
After upgrading to the latest version of `flask` and `werkzeug` some tests in the `web` test suite are failing. Some investigation revealed that there seems to be an issue with `werkzeug` reading a `JSON object`. This happens while a GET request object is built:
```
'Traceback (most recent call last):\n  File "/home/lorenz/.cache/pypoetry/virtualenvs/planetmint-LOuuP4oM-py3.9/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 598, in get_json\n    rv = self.json_module.loads(data)\n  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads\n    return _default_decoder.decode(s)\n  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode\n    raise JSONDecodeError("Expecting value", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/lorenz/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_resolver.py", line 189, in _get_py_dictionary\n    attr = getattr(var, name)\n  File "/home/lorenz/.cache/pypoetry/virtualenvs/planetmint-LOuuP4oM-py3.9/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 548, in json\n    return self.get_json()\n  File "/home/lorenz/.cache/pypoetry/virtualenvs/planetmint-LOuuP4oM-py3.9/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 607, in get_json\n    rv = self.on_json_loading_failed(e)\n  File "/home/lorenz/.cache/pypoetry/virtualenvs/planetmint-LOuuP4oM-py3.9/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 629, in on_json_loading_failed\n    raise BadRequest(f"Failed to decode JSON object: {e}")\nwerkzeug.exceptions.BadRequest: 400 Bad Request: Failed to decode JSON object: Expecting value: line 1 column 1 (char 0)\n'
``` 

I've also tried to downgrade to `flask@^2.1.0` and the respective werkzeug dependency but that did not resolve the issue as well. [werkzeug change log](https://werkzeug.palletsprojects.com/en/2.2.x/changes/)
