### ISSUE TITLE
Fail to start Tarantool and Planetmint with `docker-compose`

### ISSUE THREAD

**Issue by getlarge** [planetmint/planetmint#299]
# Description

I tried to run Planetmint using docker-compose.yaml (and the associated Dockerfile-dev) but ran into an issue at start.

1. The current Tarantool image is not compatible on Mac M1, but simply upgrading to `tarantool/tarantool:2.10.4` seems to do th trick, ([known issue](https://github.com/tarantool/docker/issues/206)
2. The Planetmint container fails to start due to what seems to be a dependency issue (i'm not a Python guy so i can only guess from the logs copied below).

```
planetmint-planetmint-1  | During handling of the above exception, another exception occurred:
planetmint-planetmint-1  | 
planetmint-planetmint-1  | Traceback (most recent call last):
planetmint-planetmint-1  |   File "/usr/local/bin/planetmint", line 33, in <module>
planetmint-planetmint-1  |     sys.exit(load_entry_point('Planetmint', 'console_scripts', 'planetmint')())
planetmint-planetmint-1  |   File "/usr/local/bin/planetmint", line 25, in importlib_load_entry_point
planetmint-planetmint-1  |     return next(matches).load()
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/importlib/metadata.py", line 86, in load
planetmint-planetmint-1  |     module = import_module(match.group('module'))
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
planetmint-planetmint-1  |     return _bootstrap._gcd_import(name[level:], package, level)
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
planetmint-planetmint-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
planetmint-planetmint-1  |   File "/usr/src/app/planetmint/__init__.py", line 10, in <module>
planetmint-planetmint-1  |     from planetmint.lib import Planetmint
planetmint-planetmint-1  |   File "/usr/src/app/planetmint/lib.py", line 53, in <module>
planetmint-planetmint-1  |     from planetmint import backend, config_utils, fastquery
planetmint-planetmint-1  |   File "/usr/src/app/planetmint/config_utils.py", line 26, in <module>
planetmint-planetmint-1  |     from pkg_resources import iter_entry_points, ResolutionError
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
planetmint-planetmint-1  |     def _initialize_master_working_set():
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
planetmint-planetmint-1  |     f(*args, **kwargs)
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
planetmint-planetmint-1  |     working_set = WorkingSet._build_master()
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
planetmint-planetmint-1  |     return cls._build_from_requirements(__requires__)
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
planetmint-planetmint-1  |     dists = ws.resolve(reqs, Environment())
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
planetmint-planetmint-1  |     raise DistributionNotFound(req, requirers)
planetmint-planetmint-1  | pkg_resources.DistributionNotFound: The 'planetmint-transactions>=0.5.0' distribution was not found and is required by Planetmint
planetmint-planetmint-1  | + [[ '' == \e\n\a\b\l\e ]]
planetmint-planetmint-1  | + planetmint -l DEBUG start
planetmint-planetmint-1  | Traceback (most recent call last):
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
planetmint-planetmint-1  |     ws.require(__requires__)
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
planetmint-planetmint-1  |     needed = self.resolve(parse_requirements(requirements))
planetmint-planetmint-1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
planetmint-planetmint-1  |     raise VersionConflict(dist, req).with_context(dependent_req)
planetmint-planetmint-1  | pkg_resources.ContextualVersionConflict: (planetmint-transactions 0.4.1 (/usr/local/lib/python3.9/site-packages), Requirement.parse('planetmint-transactions>=0.5.0'), {'Planetmint'})
```

Removing this [line](https://github.com/planetmint/planetmint/blob/main/Dockerfile-dev#L37) (eg `RUN pip install planetmint-transactions@git+https://git@github.com`) seems to do the trick as well.

**Comment by LaurentMontBlanc** [comment]
@getlarge thanks for filing this. The `RUN pip install` statement was only for development and should be reversed. I'll do it right away.

**Comment by getlarge** [comment]
thanks for fixing the issues
