### ISSUE TITLE
WS service went down and took abci with it

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint#369]
```
Mar 29 21:41:46 node8-rddl-testnet planetmint[52572]: [2023-03-29 21:41:46] [ERROR] (aiohttp.server) Error handling request (planetmint_ws - pid: 52572)
Mar 29 21:41:46 node8-rddl-testnet planetmint[52572]: Traceback (most recent call last):
Mar 29 21:41:46 node8-rddl-testnet planetmint[52572]:   File "/home/rddl/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
Mar 29 21:41:46 node8-rddl-testnet planetmint[52572]:     messages, upgraded, tail = self._request_parser.feed_data(data)
Mar 29 21:41:46 node8-rddl-testnet planetmint[52572]:   File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
Mar 29 21:41:46 node8-rddl-testnet planetmint[52572]: aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
Mar 29 21:41:46 node8-rddl-testnet planetmint[52572]: [2023-03-29 21:41:46] [INFO] (aiohttp.access) 94.232.45.23 [29/Mar/2023:21:41:46 +0000] "UNKNOWN / HTTP/1.0" 400 204 "-" "-" (planetmint_ws - pid: 52572)

```

**Comment by eckelj** [comment]
on my environment, the wrong WS requests do not take there service down.
