### ISSUE TITLE
Bug: planetmint crash on node4 1st of april

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint#374]
```
, 'metadata': None, 'assets': [{'data': 'bafkreig5mzpohexj4itfbsisosszzn4ps5m7yoxb7bwkegmrldqkgc5t5i'}], 'version': '3.0', 'id': 'df9a2071f2d2a7f58792ad19c99c691fba29ec86f577e0699d6710f50c3225e3'} (planetmint_webapi - pid: 180116)
[2023-04-01 00:15:04] [ERROR] (asyncio) Task exception was never retrieved
future: <Task finished name='Task-9' coro=<ABCIServer._handler() done, defined at /home/rddl/venv/lib/python3.9/site-packages/abci/server.py:163> exception=SystemExit(1)> (MainProcess - pid: 180079)
Traceback (most recent call last):, 'metadata': None, 'assets': [{'data': 'bafkreig5mzpohexj4itfbsisosszzn4ps5m7yoxb7bwkegmrldqkgc5t5i'}], 'version': '3.0', 'id': 'df9a2071f2d2a7f58792ad19c99c691fba29ec86f577e0699d6710f50c3225e3'} (planetmint_webapi - pid: 180116)
[2023-04-01 00:15:04] [ERROR] (asyncio) Task exception was never retrieved
future: <Task finished name='Task-9' coro=<ABCIServer._handler() done, defined at /home/rddl/venv/lib/python3.9/site-packages/abci/server.py:163> exception=SystemExit(1)> (MainProcess - pid: 180079)
Traceback (most recent call last):
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/backend/tarantool/sync_io/query.py", line 50, in wrapper
    output = function_to_decorate(*args, **kw)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/backend/tarantool/sync_io/query.py", line 183, in get_transaction_by_id
    txs = connection.connect().select(table, transaction_id, index=TARANT_ID_SEARCH)
  File "/home/rddl/venv/lib/python3.9/site-packages/tarantool/connection.py", line 2037, in select
    response = self._send_request(request, on_push, on_push_ctx)
  File "/home/rddl/venv/lib/python3.9/site-packages/tarantool/connection.py", line 1250, in _send_request
    return self._send_request_wo_reconnect(request, on_push, on_push_ctx)
  File "/home/rddl/venv/lib/python3.9/site-packages/tarantool/connection.py", line 1137, in _send_request_wo_reconnect
    response = request.response_class(self, self._read_response())
  File "/home/rddl/venv/lib/python3.9/site-packages/tarantool/response.py", line 119, in __init__
    self._sync = header.get(IPROTO_SYNC, 0)
AttributeError: 'int' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/abci/application_logic.py", line 161, in check_tx
    if self.validator.is_valid_transaction(transaction):
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/application/validator.py", line 500, in is_valid_transaction
    return self.validate_transaction(tx, current_transactions)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/application/validator.py", line 152, in validate_transaction
    self.validate_create_inputs(transaction, current_transactions)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/application/validator.py", line 117, in validate_create_inputs
    if self.models.is_committed(tx.id) or duplicates:
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/model/dataaccessor.py", line 45, in is_committed
    transaction = backend.query.get_transaction_single(self.connection, transaction_id)
  File "/usr/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/backend/tarantool/sync_io/query.py", line 191, in get_transaction_single
    txs = get_complete_transactions_by_ids(txids=[transaction_id], connection=connection)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/backend/tarantool/sync_io/query.py", line 78, in get_complete_transactions_by_ids
    tx = get_transaction_by_id(connection, txid, TARANT_TABLE_TRANSACTION)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/backend/tarantool/sync_io/query.py", line 62, in wrapper
    raise DBConcurrencyError
planetmint.backend.exceptions.DBConcurrencyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 147, in run
    loop.run_until_complete(self._start())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 192, in _handler
    response = self.protocol.process(req_type, message)
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 36, in process
    return handler(req)
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 48, in check_tx
    result = self.app.check_tx(req.check_tx.tx)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/abci/application_logic.py", line 168, in check_tx
    sys.exit(1)
SystemExit: 1
[2023-04-01 21:45:05] [ERROR] (asyncio) Task exception was never retrieved
future: <Task finished name='Task-10' coro=<ABCIServer._handler() done, defined at /home/rddl/venv/lib/python3.9/site-packages/abci/server.py:163> exception=TypeError("'NoneType' object is not subscriptable")> (MainProcess - pid: 191869)
Traceback (most recent call last):
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 192, in _handler
    response = self.protocol.process(req_type, message)
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 36, in process
    return handler(req)
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 73, in end_block
    result = self.app.end_block(req.end_block)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/abci/application_logic.py", line 244, in end_block
    self.block_txn_hash = calculate_hash([block["app_hash"], block_txn_hash])
TypeError: 'NoneType' object is not subscriptable

  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/backend/tarantool/sync_io/query.py", line 50, in wrapper
    output = function_to_decorate(*args, **kw)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/backend/tarantool/sync_io/query.py", line 183, in get_transaction_by_id
    txs = connection.connect().select(table, transaction_id, index=TARANT_ID_SEARCH)
  File "/home/rddl/venv/lib/python3.9/site-packages/tarantool/connection.py", line 2037, in select
    response = self._send_request(request, on_push, on_push_ctx)
  File "/home/rddl/venv/lib/python3.9/site-packages/tarantool/connection.py", line 1250, in _send_request
    return self._send_request_wo_reconnect(request, on_push, on_push_ctx)
  File "/home/rddl/venv/lib/python3.9/site-packages/tarantool/connection.py", line 1137, in _send_request_wo_reconnect
    response = request.response_class(self, self._read_response())
  File "/home/rddl/venv/lib/python3.9/site-packages/tarantool/response.py", line 119, in __init__
    self._sync = header.get(IPROTO_SYNC, 0)
AttributeError: 'int' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/abci/application_logic.py", line 161, in check_tx
    if self.validator.is_valid_transaction(transaction):
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/application/validator.py", line 500, in is_valid_transaction
    return self.validate_transaction(tx, current_transactions)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/application/validator.py", line 152, in validate_transaction
    self.validate_create_inputs(transaction, current_transactions)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/application/validator.py", line 117, in validate_create_inputs
    if self.models.is_committed(tx.id) or duplicates:
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/model/dataaccessor.py", line 45, in is_committed
    transaction = backend.query.get_transaction_single(self.connection, transaction_id)
  File "/usr/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/backend/tarantool/sync_io/query.py", line 191, in get_transaction_single
    txs = get_complete_transactions_by_ids(txids=[transaction_id], connection=connection)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/backend/tarantool/sync_io/query.py", line 78, in get_complete_transactions_by_ids
    tx = get_transaction_by_id(connection, txid, TARANT_TABLE_TRANSACTION)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/backend/tarantool/sync_io/query.py", line 62, in wrapper
    raise DBConcurrencyError
planetmint.backend.exceptions.DBConcurrencyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 147, in run
    loop.run_until_complete(self._start())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 192, in _handler
    response = self.protocol.process(req_type, message)
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 36, in process
    return handler(req)
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 48, in check_tx
    result = self.app.check_tx(req.check_tx.tx)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/abci/application_logic.py", line 168, in check_tx
    sys.exit(1)
SystemExit: 1
[2023-04-01 21:45:05] [ERROR] (asyncio) Task exception was never retrieved
future: <Task finished name='Task-10' coro=<ABCIServer._handler() done, defined at /home/rddl/venv/lib/python3.9/site-packages/abci/server.py:163> exception=TypeError("'NoneType' object is not subscriptable")> (MainProcess - pid: 191869)
Traceback (most recent call last):
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 192, in _handler
    response = self.protocol.process(req_type, message)
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 36, in process
    return handler(req)
  File "/home/rddl/venv/lib/python3.9/site-packages/abci/server.py", line 73, in end_block
    result = self.app.end_block(req.end_block)
  File "/home/rddl/venv/lib/python3.9/site-packages/planetmint/abci/application_logic.py", line 244, in end_block
    self.block_txn_hash = calculate_hash([block["app_hash"], block_txn_hash])
TypeError: 'NoneType' object is not subscriptable

```

**Comment by eckelj** [comment]
should be solved by deploying planetmint version 2.4.5
